### ISSUE TITLE
Optimization flags should not be package specific

### ISSUE THREAD

**Issue by xubaiw** [tydeu/lean4-lake#19]
https://github.com/leanprover/lake/blob/111a47f8964088aa452aa0fcdd0c1d88562cca68/Lake/Package.lean#L179-L184

Lake is currently specifying default optimization flags to `-O3 -DNDEBUG`, which would cause a problem when there is package dependencies, since a package cannot override the `leancArgs` of the package it depends on. Optimization level should be a global choice and users can simply change it using command line args.

**Comment by tydeu** [comment]
@xubaiw @Kha I am a bit confused as to the logic here. Why would you want to modify the the compilation of dependent packages? If a dependent package asserts that it is to be compiled with `-O3`, `-DNDEBUG` (or any other flags) I think it would be very concerning for the parent package to override that without its permission. Furthermore, just because one wants to build the package they are developing with a low optimization level and debug symbols that doesn't mean they want to build all dependencies that way as well.

However, if a dependent package wants to make the optimization level of a package modifiable by end users, it could so with something like:

```lean
package A (dir) (args) {
  leancArgs := if args.isEmpty then #["-O3", "-DNDEBUG"] else args.toArray
  ...
}

package B {
  dependencies := #{{name := `A, args := #["-O1"], ...}]
  ...
}
```

**Comment by xubaiw** [comment]
So debug info of the dependencies is unnecessary? Maybe I have mistaken it, I see `cargo` just rebuilds all dependencies when I switch from `cargo build` to `cargo build --release`. Are we assuming there's no bug in dependent packages?

Besides, something like [profile](https://doc.rust-lang.org/cargo/reference/profiles.html) in `cargo` and [build type](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) in `cmake` is a higher level concept than compiler flags. Although it's unrealistic and unnecessary to modify the compilation of dependent packages, some standard profiles (which can be configured by the dependent package) like `Debug`, `Release`, `MinSizeRelease` can be helpful. Should we have something alike, or is this considered a bad practice for Lean?

**Comment by Kha** [comment]
Yes, offering a choice of build profiles independent from the specific package configuration is standard practice in any package manager for a compiled language. Whether dependencies should be built in debug mode as well (and whether debug or release should be the default) seems to be [a contentious topic](https://github.com/rust-lang/cargo/issues/784), but "make as much of the program debuggable as possible in debug mode" looks like a fine default to me. Bad enough that most languages only ship a precompiled, optimized stdlib... :) .

**Comment by tydeu** [comment]
@xubaiw @Kha I don't disagree that build profiles are good. But as you mentioned @Kha, enforcing them on dependencies is questionable. More important, this is the `leanc` build we are talking about -- i.e., the compilation of the resulting `.c` files produced by Lean. So, unless Lean itself has bug (or you are debugging an external FFI), there should not be a need to debug these programs. Thus, when/if Lake supports build profiles I would expect them to apply to compiling the Lean code itself, not its intermediary results.

**Comment by xubaiw** [comment]
Yes, it's too early to talk about debugging in Lean. You can close this issue if Kha has no further questions.

**Comment by Kha** [comment]
I think for now the most important part is to ensure that introducing build profiles is backward compatible. Users shouldn't need to change their package configuration for this, nor should they hard-code `-O3 -NDEBUG` when changing `leancArgs`. The latter could be done by always prefixing these flags for now, which can be negated by the user using `-O0 -UDEBUG`.
