### ISSUE TITLE
Add `lake clean` command

### ISSUE THREAD

**Issue by xubaiw** [tydeu/lean4-lake#2]
In the examples Lake uses "clean.sh" script to remove the build directory. Consider adding `lake clean` command to make it more practical and clearer.

**Comment by xubaiw** [comment]
The clean command may simply remove the build directory.
```Lean
-- new file Clean.lean
partial def removeRecursively (p : FilePath) : IO Unit := do
  unless ← p.pathExists do return ()
  if ← p.isDir then do
    for f in ← p.readDir do
      removeRecursively f.path
  IO.FS.removeFile p
  return ()

def clean (self : Package) : IO Unit := do
  removeRecursively self.config.buildDir  -- though currently buildDir cannot be specified in PackageConfig
  -- may be some try except here

def clean (pkg : Package) : IO PUnit :=
  pkg.clean


-- Cli.lean
import Lake.Clean

def cli : (cmd : String) → (lakeArgs pkgArgs : List String) → IO Unit
  | "clean", _, _ => do clean (← getCwdPkg pkgArgs)
  | _, _, _ => -- other commands omitted
```

**Comment by tydeu** [comment]
The problem with adding built-in support for this to Lean is that, as you surmised, there is no defined build directory to delete. The various output directories do not all have to be within some central build directory.

However, you can currently add this feature to a package yourself by adding a `clean` script to your package configuration:

```lean
import Lake.Package
open Lake System Std

partial def removeRecursively (p : FilePath) : IO Unit := do
  unless ← p.pathExists do return ()
  if ← p.isDir then do
    for f in ← p.readDir do
      removeRecursively f.path
  IO.FS.removeFile p
  return ()

def buildDir : FilePath := "build"

def package : PackageConfig := {
  name := "simpleAdd"
  version := "0.1"
  scripts :=
    HashMap.empty.insert "clean" fun _ => do
      removeRecursively buildDir
}
```

You can then run this script with `lake run clean`.

**Comment by tydeu** [comment]
I went ahead and introduce the notion of a build directory and added a `lake command` anyway (see 53bb08fb92114e9d196d88e355c84b06312ac2df). :)
