### ISSUE TITLE
Allowing "package.lean" not in package root

### ISSUE THREAD

**Issue by xubaiw** [tydeu/lean4-lake#4]
Allowing `package.lean` not in package root like this
```bash
$ tree
.
├── Foo
│   └── Bar.lean
├── Foo.lean
├── lake
│   └── package.lean
└── leanpkg.toml
```
will bring us at least *3 benefits*:
1. **LeanPkg package and Lake package at the same time**: LeanPkg is the official package manager for Lean, and it does't allow two "*.lean" files in the root directory. A repository cannot be both LeanPkg package and Lake package at the same time, and people have to choose between them. If non-top-level "package.lean" is allowed, this will not be a problem. And those repos that currently use LeanPkg can easily add support for Lake without breaking things.
2. **Lake can be used as dependency**: If non-top-level "package.lean" is allowed and Lake itself can have a "package.lean", Lake can be use as dependency in "package.lean". In this situation, we can have `compileCMake`, `compileCargo` convenience functions derived from `Lake.proc` in "lake-cmake", "lake-cargo" packages, etc., which can save us from the chores of writing build processes when the package uses large and complex FFI libraries (devDependencies and buildDependencies features is also needed).
3. **LSP lint support**: The VSCode extension "vscode-lean4" does not support importing when we uses "package.lean". If we place a "leanpkg.toml" in package root and "package.lean" in subdirectory we can cheat the extension and avoid writing new LSP and extension.

The difficulty is on how to resolve the package if the "package.lean" is not in package root. There are two possible solutions. Currently `Lake` resolves the package like this:
```Lean
-- Cli.lean
def getCwdPkg (args : List String) : IO Package := do
  let pkg ← Package.fromDir "." args  -- **This line** get current package from "."
  if pkg.leanVersion ≠ leanVersionString then
    IO.eprintln $ "\nWARNING: Lean version mismatch: installed version is " ++
      leanVersionString ++ ", but package requires " ++ pkg.leanVersion ++ "\n"
  return pkg

-- Resolve.lean
def solveDepsCore (pkg : Package) : (maxDepth : Nat) → Solver Unit
  | 0 => throw <| IO.userError "maximum dependency resolution depth reached"
  | maxDepth + 1 => do
    let newDeps ← pkg.dependencies.filterM (notYetAssigned ·.name)
    for dep in newDeps do
      let dir ← materialize pkg dep
      let pkg ← Package.fromDir dir dep.args -- **This line** get dependent packages from `dir`
      modify (·.insert dep.name pkg)
    for dep in newDeps do
      let depPkg ← resolvedPackage dep.name
      unless depPkg.name = dep.name do
        throw <| IO.userError <|
          s!"{pkg.name} (in {pkg.dir}) depends on {dep.name}, " ++
          s!"but resolved dependency has name {depPkg.name} (in {depPkg.dir})"
      solveDepsCore depPkg maxDepth
```
1. The first solution is to *also* look for "package.lean" in "./lake" and `dir / "lake"`, which use "lake" subdirectory as alternative search path.
2. The second solution involves adding new field to dependencies to manually specify the custom `package.lean` path.
```Lean
-- Package.lean
structure Dependency where
  name : String
  src  : Source
  args : List String := []
  configPath : Option String := none -- **Add new field to Dependency**
```
Actually, this two approach can be combined together, that is to first search in`Dependency.configPath` then the package root "." and at last the "./lake" subdirectory.

**Comment by tydeu** [comment]
For (1), you may already be able to resolve this by running Lake in the directory of your `package.lean` (i.e `./lake` in your example) and setting the `srcDir` of your package configuration to the parent directory (i.e. 'srcDir := ..').

For (2), this is very similar to one of the changes I had been planning, so this feature should land in master soon.

**Comment by tydeu** [comment]
As my edits to my previous post hopefully conveyed, this should all be doable now. So please take a look and see if you are satisfied with my solutions. :)

**Comment by xubaiw** [comment]
Thanks! 
As Lake's configuration is becoming more powerful and complex, I think it's time to have some detailed documentation. Maybe I can help with this. In my plan, the doc will be of two parts, the first of which may include several ready-to-use examples, and the second part is about important types and functions of Lake, so that newcomers can get a basic understanding of Lake without reading through the source code.

**Comment by xubaiw** [comment]
There's still a bug in revision 39c463636b17f690caa9cb5d1fa686a80698d936.
The `lean build-bin` command got stuck when I run it in "./lake".
```sh
$ tree 
.
├── Foo
│   └── Bar.lean
├── Foo.lean
├── lake
│   └── package.lean
└── leanpkg.toml
```
And My "package.lean" config is like this
```Lean
def package : Lake.PackageConfig := {
  name := "foo"
  version := "0.1"
  leanVersion := "leanprover/lean4:nightly-2021-07-28"
  rootDir := ".."
  buildDir := "../build"
}
```
The command got stuck with no output and I am not sure where the problem comes from.

**Comment by tydeu** [comment]
@xubaiw I created a new issue for this bug (see #5). Was the `lean_version` in the `leanpkg.toml` the same as the `leanVersion` in your `package.lean`? Also do both match the version of Lean, lake was built with? If not, I suspect this the same bug as #3.

**Comment by tydeu** [comment]
@xubaiw On your documentation point: While I appreciate the offer, I don't think Lake is quite ready for API docs. I still need to do at least one more major API refactor before I am happy with build system interface. After that, docs will be high priority and I would certainly appreciate any contributions.
